# Tópicos Especiais em Processamento da Informação: Ciência de Dados

Prof. Luiz Affonso Guedes

Engenharia de Computação - UFRN
2017-2

# Pacote Numpy
- Pacote com diversas operações sobre coleções diversas
- Alternativa de arrays para listas, mas são mais eficientes computacionalmente que as listas.
- Elementos de Arrays em Numpy, diferentemente de listas, possuem o mesmo tipo.
   - Por isto, arrays são mais eficientes que listas.

NumPy3 é o pacote básico para computação científica com o Python. NumPy fornece, entre outras coisas, suporte para matrizes multidimensionais com operações básicas sobre elas e funções de álgebra linear úteis. 

- Muitos outros pacotes Python usam as representações da matriz NumPy como uma estrutura de dados básica eficiente. 

- O SciPy fornece uma coleção de algoritmos numéricos e toolboxs específicos do domínio, incluindo processamento de sinais, otimização, estatísticas e muito mais. 

    - Um toolbox básico no SciPy é a biblioteca para traçar gráficos Matplotlib. Este toolbox possui muitas ferramentas para visualização de dados.

In [1]:
# importando o pacote numpy e verificando a sua versão.
import numpy
numpy.__version__

'1.13.1'

In [3]:
# Por hábito e simplicidade, o pacote numpy é utilizado com o alias np 
import numpy as np

In [ ]:
# Para verificar o conteúdo do pacote
np?

Não podemos esquecer que em Python todas as variáveis são tipadas dinamicamente. Assim, a cada variável é atribuída mais informação além de seu conteúdo. 
 - Como Python é implementado em C, cada variável Python é implementada com uma estrutura em C.
     - Isto acarreta overhead.
     - Em tipos complexo, como lista, a eficiência pode ficar muito comprometida quando se tem grandes dimensões nos dados.
     
- Dilema entre flexibilidade e desempenho
    - Se uma lista possuir só elementos de um mesmo tipos, podemos tornar o manuseio dessa variável mais eficiente.
    - Arrays em Numpy são "listas" cujos elementos são do mesmo tipo.
        - Objeto ndarray no pacote Numpy.
    - Há um pacote com tipo array em Python.

In [ ]:
# Exemplo de uso do tipo array (Não é o Array do Numpy)
import array
L = list(range(10))
A = array.array('i', L) # i designa que a variável é do tipo inteiro
print(type(A))
print(A)

In [ ]:
# Exemplo de uso do tipo Array do Pacote Numpy (objeto ndarray)
import numpy as np
# array de inteiros:
A = np.array([1, 4, 2, 5, 3])
print(type(A))
print(A)

In [ ]:
# O Numpy tentará transformar todos os elementos paar um mesmo tipo de dados
A2 = np.array([3.14, 4, 2, 3])
print(type(A2))
print(A2)

In [ ]:
# É Possível determinar o tipo do dado
A3 = np.array([1, 2, 3, 4], dtype='float32')
print(type(A3))
print(A3)

In [4]:
# Arrays em Numpy podem ser explicitamete multidimencionais
# Exemplo de iniciação de Array como lista de lista
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Incializações típicas de Arrays:
- np.zeros(dimensao, dtype=tipo_de_variavel)
- np.ones(dimensao, dtype=tipo_de_variavel)
- np.full(dimensao, valor)

In [ ]:
# Exemplo de iniciação de Arrays Numpy
array1 = np.zeros(10, dtype=int)
array2 = np.ones((3, 5), dtype=float)
array3 = np.full((3, 5), 3.14)

print("array1")
print(array1)
print("array2")
print(array2)
print("array3")
print(array3)

In [ ]:
# Exercício 01 - crie 03 arrays Numpy
# array1, de dimensão 7 por 2, com todos elementos iguais a 2.1
# array2, vetor de dimensão 10, com todos os valores igauis a 1 em ponto flotuante
# array3, de dimensão 2 por 3 por 4, com todos os valores iguais a zero 
array1 = ?????
array2 = ?????
array3 = ?????
print(array1)
print(array2)
print(array3)

In [ ]:
print("Outros exemplos de iniciação de Arrays Numpy")
print("Infira o que faz cada tipo de iniciação")

array1 = np.arange(0, 20, 2)
array2 =np.linspace(0, 1, 5)
array3 = np.eye(3)

print("array1")
print(array1)
print("array2")
print(array2)
print("array3")
print(array3)

In [ ]:
print("Os Arrays NumPy também podem ser inicializados de forma randômica")
media = 0
desvio_padrao = 1
num_linhas = 3
num_colunas = 3
inicio = 0 # início do intervalo da distribuição linear - fechado
fim = 2    # fim do intervalo da distribuição linear - aberto
           # o intervalo é [inicio, fim)

array1 = np.random.normal(media,desvio_padrao, (num_linhas, num_colunas))
array2 = np.random.random((num_linhas, num_colunas))
array3 = np.random.randint(inicio,fim, (num_linhas, num_colunas))

print("array1 - Iniciação randômica seguindo distribuição Normal")
print(array1)
print("array2 - Iniciação randômica seguindo distribuição Uniforme ente 0 e 1")
print(array2)
print("array3 - Iniciação randômica com números inteioros")
print(array3)

In [ ]:
# Exemplos de iniciação ramdômica de arrays Numpy
import numpy as np

np.random.seed(0) # Inciação da semente randômica
x1 = np.random.randint(10, size=6) # Array unidimensional
x2 = np.random.randint(10, size=(3, 4)) # Array bi-dimensional
x3 = np.random.randint(10, size=(3, 4, 5)) # Array tri-dimensional

# Exemplos de de métodos para informar os tipos de dados dos Arrays

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype:", x3.dtype)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

Acesso de elementos e seguimentos de Array Numpy
- Segue o mesmo modo de acesso em lista

In [ ]:
# Array x1, definido anteriormente
print(x1)
print(type(x1))
x1

In [ ]:
# Exemplos de acesso de elementos de um array Numpy unidimensional
print("Array x1 --> ", x1)
print("x1[0] = ", x1[0])
print("x1[-1] = ", x1[-1])
print("x1[-2] = ", x1[-2])
#print("x1[-7] = ", x1[-7])  # Isto irá funcionar???

In [ ]:
# Array x2, definido anteriormente
print(x2)
print(type(x2))


In [ ]:
# Exemplos de acesso de elementos de um array Numpy multidimensional
print("x2[0,0]  = ", x2[0,0])
print("x2[2,-1] =  ",x2[2,-1])
x2[0,0] = 10
x2[2,-1] = 2.345
print("x2[0,0]  = ", x2[0,0])
print("x2[2,-1] =  ",x2[2,-1])  # será um número inteiro ou ponto flutuante?

In [ ]:
# Exemplos de acesso de sub-arraays de um array Numpy unidimensional
x = np.arange(10)
print("x       = ", x)
print("x[0:2]  = ", x[0:2])
print("x[2:-1] = ", x[2:-1])
print("x[:-1]  = ", x[:-1])
print("x[1:]   = ", x[1:])
print("x[:]    = ", x[:])

In [ ]:
# Exemplos de acesso de vários elementos um array Numpy unidimensional
x = np.arange(10)
print("x       = ", x)
print()
print("x[::2]  = ", x[::2]) # acesso desde o primeiro elemento com passo 2
print("x[::3]  = ", x[::3]) # acesso desde o primeiro elemento com passo 3
print("x[1::2] = ", x[1::2]) # acesso desde o segundo elemento com passo 2
print("x[::-1] = ", x[::-1]) # acesso os elemento de modo reverso
print("x[6::-2]= ", x[6::-2]) # acesso desde o sexto os elemento com passo -2
print()
print("x[1:8:2]= ", x[1:8:2]) # caso geral


In [ ]:
# Exercício - acesso de sub-arraays de um array Numpy multidimensional
print("x2 = ")
print(x2)

In [ ]:
print("x2[:2, :3] = ")
print(x2[:2, :3])

In [ ]:
print("x2[:3, ::2] = ")
print(x2[:3, ::2])


In [ ]:
# Exercício - Obtenha de sub-arrays multidimensionais
print("Dada a matriz x2.")
print("Obter uma sub matriz que corresponde às linhas ímpares e as colunas pares, escritas de modo reservo.")
# ínicio do código

# fim do código

Um ponto muito importante é que sub-arrays em Numpy não fazem cópia do array original, mas sim são visões (referências aos mesmos espaços de endereço).
- Isto se deve por questão de eficiência.
- Em lista, ao contrário de Arrays, sub-listas são cópias de elementos da lista original.

Os exemplos abaixo evidenciam isto.

In [ ]:
# Exemplos de sub-arrays como vistas dos arrays originais
print("x2 = ")
print(x2)

x2_sub = x2[:2, :2]
print()
print("x2_sub")
print(x2_sub)

x2_sub[0, 0] = 99
print()
print("x2_sub[0, 0] = 99")
print(x2_sub)

print("")
print("Novos valores para x2")
print("x2 = ")
print(x2)

In [ ]:
print("Como, então, se pode fazer cópia de arrays Numpy?")

In [ ]:
print("Cópias de Arrays Numpy são realizados via o método .copy()")
print("x2 = ")
print(x2)

x2_sub_copy = x2[:2, :2].copy()
print()
print("x2_sub_copy")
print(x2_sub_copy)

x2_sub_copy[0, 0] = 42
print()
print("x2_sub_cop - atribuir 42 para a posição [0,0]")
print(x2_sub_copy)

print()
print("Verificação dos valores de x2")
print(x2)

In [ ]:
# Concatenação de Arrays Numpy

x = np.array([1, 2, 3])
y = np.array([4, 5])
z = np.array([6,7,8,9])
w = np.concatenate([x, y,z])
print("w = ")
print(w)

In [ ]:
# Concatenação de Arrays bidimensionais Numpy - Matrizes
mat1 = np.array([[1, 2, 3],[4, 5, 6]])
print("mat1 = ")
print(mat1)

mat2 = np.concatenate([mat1,mat1])
print()
print("mat2 = ")
print(mat2)

mat3 = np.concatenate([mat1,mat1], axis=1)
print()
print("mat3 = ")
print(mat3)

In [ ]:
# Separando Arrays Numpy
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3 = np.split(x, [3, 5])
print("x1, x2, x3")
print(x1, x2, x3)

y1, y2, y3, y4 = np.split(x, [2, 5, 7])
print("y1, y2, y3, y4")
print(y1, y2, y3, y4)


In [ ]:
# Exercício - Divida o array vet em outros 5 de mesmo tamanho

vet = [1,2,3,4,5,6,7,8,9,10]
print("????")

Programando eficientemente em Python
- Python é uma linguagem interpretada, escrita em C.
- Chamada de métodos em Python levam a chamadas de funções em C.
- Programação vetorizada aumenta consideravelmente o desempenho dos programas Python.
    - usa funções com tipos pré-tipados

In [2]:
# Exemplo de programação estilo escalar 
# Função para obter os valores recíprocos (inversos) dos eementos de um Array Numpy

import numpy as np

np.random.seed(0)

def calcular_reciprocos(values):
  output = np.empty(len(values))
  for i in range(len(values)):
   output[i] = 1.0 / values[i]
  return output

valores = np.random.randint(1, 10, size=5)
valores_inversos = calcular_reciprocos(valores)
print(valores_inversos)

[ 0.16666667  1.          0.25        0.25        0.125     ]


In [4]:
# Exemplo - Medição de tempo gasto para executar a função calcular_reciprocos(.) 
big_array = np.random.randint(1, 100, size=1000000)
%timeit calcular_reciprocos(big_array)

1 loop, best of 3: 2.43 s per loop


In [5]:
# Exemplo de programação vetorizada

print(calcular_reciprocos(valores))  # programação escalar
print()
print(1.0 / valores)                 # programação vetorizada


[ 0.16666667  1.          0.25        0.25        0.125     ]

[ 0.16666667  1.          0.25        0.25        0.125     ]


In [ ]:
# Exemplo: medição de tempo de programação vetorizada
%timeit (1.0 / big_array)

In [10]:
# Exemplo de programação vetorizada
print("Você pode explicar o que faz a linha de código abaixo?")
x = 2 ** np.arange(9).reshape((3, 3))
print(x)

x1 = np.arange(9)
x1.reshape((3,3))
x1 = 2 ** x1
print(x1.reshape((3,3)))

Você pode explicar o que faz a linha de código abaixo?
[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]
[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


Os operadores matemáticos em Numpy operam elemento a elemento
- Mais a frente veremos como implementar operações matriciais, no estilo Matlab.
- Exemplos de operadores matemáticos sobre arrays
        - +, - , *,/, **, //, % 


In [ ]:
# Exemplo de programação vetorizada

x = np.array([1,2,3,4])
y1 = 2*x
y2 = x * 2
y3 = x * x
y4 = x ** x
print("x = ")
print(x)
print()
print("x + 10 = ")
print(x + 10)
print()
print("-(0.5*x) + 2 = ")
print(-(0.5*x) + 2 )
print()
print("y1 = ")
print(y1)
print()
print("y2 = ")
print(y2)
print()
print("y3 = ")
print(y3)
print()
print("y4 = ")
print(y4)

Operadores matemáticos são chamadas de métodos em Numpy
- Operador Adição (+) , equivale a np.add Addition (por exemplo, 1 + 1 = 2)
- Operador Subtração (-),equivale a np.subtract Subtraction (por exemplo, 3 - 2 = 1)
- Operador Nagativo Unário (-), equivale a np.negative (por exemplo, -2)
- Operador Multiplicação (*), equivale a np.multiply (por exemplo, 2 * 3 = 6)
- Operador Divisão (/), equivale a np.divide (por exemplo, 3 / 2 = 1.5)
- Operador Divisão Inteira (//), equivale a np.floor_divide (por exemplo, 7 // 2 = 3)
- Operador Exponenciação, equivale a np.power
- Operador módulo (%), equivale a np.mod (por exemplo, 7 % 2 = 1)

In [ ]:
# Exmplo de método associado com operador
print("x = ")
print(x)

print()
print("x + 10 = ")
print(np.add(x, 10))

print()
print("x ** 2 = ")
print(np.power(x, 2))


In [ ]:
# Exmplo de método associado com operador multiplicação e se especificando a variável de saída
x = np.arange(5)
y = np.empty(5)   # cria um array de 5 posições
print(y)
np.multiply(x, 10, out=y)
print(y)

Numpy possui rico suporte de funções e constantes mataméticas.
- Trigonometria
        - valor de pi --> np.pi
        - valor de e --> np.e
        - função seno --> np.sin(radiano)
        - função cosseno --> np.cos(radiano)
        - função tangente --> np.tan(radiano)
        - função arcoseno -->  np.arcsin(radiano)
        - função arcocosseno -->  np.arccos(radiano)
        - função arcotangente --> np.arctan(radiano)

In [ ]:
# Exemplos de funções trigonométricas em Numpy
print("Valor de PI --> ", np.pi)
print( "Valor de e --> ", np.e)
print( "Valor de seno(pi/2) --> ", np.sin(np.pi/2)) 

teta = np.array([0, np.pi/4, np.pi/2, np.pi*3/4, np.pi])
print("Valor de teta = ")
print(teta)
print("Valor de seno(teta) = ")
print(np.sin(teta))

Exercíco:
Dada a seguinte equação: 
$\newcommand{\sen}{{\rm sen}}$

$ y = \sqrt[2]{1 - \sen^2(k.\pi/4)} $



In [ ]:
# Exercício - Calcule e imprima o valor de y
# Sem utilização do comando for

#k = np.array(range(8))
k = np.arange(8)

#print("???????")

print(k)
print(y)

In [22]:
# Exercício - Calcule e imprima o IMC dos alunos
# 01 polegada = 2.54 cm = 0.0254 m
# 01 libra = 0.453592 Kg
# Altura dos alunos em polegadas
# IMC = Peso/Altura^2

altura_polegada = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]
peso_libra = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190, 210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235, 210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195]
# ----------------- cálculo do IMC  ----------------------
altura = np.array(altura_polenada)/2.54
peso = 453592*np.array(peso_libra)

IMC = (peso)/(altura**2)

 
# --------------------------------------------------------
print("Os valores de IMC dos alunos são:")
print(IMC)

Os valores de IMC dos alunos são:
[  1.49098904e+08   1.78090358e+08   1.83746759e+08 ...,   1.65309084e+08
   1.53213298e+08   1.65979433e+08]


Funções exponenciais e logorítmicas
- $\ e^x$ = $exp(x)$ --> np.exp(array)
- $2^x$ --> np.exp2(array)
- $b^e$ --> np.power(array_base, array_expoente)
- $ln(x)$ --> np.log(array)
- $log_2(x)$ --> np.log2(array)
- $log_{10}(x)$ --> np.log10(array)

In [ ]:
# Exemplos de uso de funções exponenciais
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(2, x))

In [ ]:
# Exemplos de uso de funções exponenciais

#print("e^x =", np.e**x)  # esta expressão está correta?

print( "e^x =", (np.e*np.ones(3))**x1)



In [ ]:
# Exemplos de uso de funções logorítmicas
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

Operações "recursivas" em Arrays Numpy
- Executam elemento a elemento recorrentemente, até percorrer todo o array.
- np.add.reduce(array) --> retorna a somatória dos elementos do array  
- np.multiply.reduce(array) --> retorna o produtório dos elementos do array 

In [ ]:
# Exemplos de uso do método reduce()
x = np.arange(1,5)
y1 = np.add.reduce(x)
y2 = np.multiply.reduce(x)

print("x = ", x)
print("y1 = ", y1)
print("y2 = ", y2)


In [ ]:
# Exemplos de uso do método .accumulate(array)
print("Que procedimento o método '.accumulate(array)' executa?")
y3 = np.add.accumulate(x)
y4 = np.multiply.accumulate(x)

print("x = ", x)
print("y3 = ", y3)
print("y4 = ", y4)

In [1]:
# Exemplos de uso do método .outer(array1, array2)
print("Que procedimento o método '.outer(array1, array2)' executa?")
x = np.arange(1,5)
x1 = np.ones(5)
y5 = np.add.outer(x, x)
print(y5)
y6 = np.multiply.outer(x, x)
y7 = np.add.outer(x, x1)

print("x = ", x,"\n")
print("x1 = ", x1,"\n")
print("y5 = ")
print(y5,"\n")
print("y6 = ")
print(y6, "\n")
print("y7 = ")
print(y7)

Que procedimento o método '.outer(array1, array2)' executa?


NameError: name 'np' is not defined

Operadores aritiméticos e lógicos entre Arrays Numpy e escalares são aplicados elemento a elemento no Array.
De forma geral, é possível realizar operações aritiméticas e lógicos com array de dimensões diferentes.
- a operação será reaizada por dimensão.

In [ ]:
# Exemplos de operações aritiméticas e lógicas com Array Numpy e escalares
x = np.array([1, 2, 3, 4, 5])
print("x < 3 \n", x<3)
print("x == 3 \n", x==3)
print("x + 3 \n", x+3)
print("x * 3 \n", x/3)

In [ ]:
# Exemplos de operações aritiméticas e lógicas 
# entre Array bidimensional e unidimensional
x1 = np.array([[1, 2, 3], [4, 5, 6]])
x2 = np.array([2,2,2])
print("x1  \n", x1)
print("x2  \n", x2)
print("x1 < 3 \n", x1<3)
print("x1 == 3 \n", x1==3)
print("x1 + x2 \n", x1+x2)
print("x1 * x2 \n", x1* x2)
print("x2 * x1 \n", x2* x1)

In [ ]:
# Exemplo de métodos sobre arrays Numpy booleanos
print(x1)
print("Número de valores menores de 3 em x1 ", np.count_nonzero(x1 < 3))
print("Número de valores menores de 3 em x1 ", np.sum(x1 < 3))
print("Por que os valores dos dois comandos print() são iguais?")

In [ ]:
# Exemplo de uso dos métodos np.all(array_booleano) e np.any(array_booleano)
print("Explique o funcionamento desses dois métodos")
print(x1)
print(np.any(x1<3))
print(np.all(x1<3))


Há diversos métodos que implementam funções estatísticas básicas para Arrays Numpy. Abaixo são apresentados alguns exemplos de uso dessas funções.

In [ ]:
# Exemplos de uso de funções estatísticas

x = np.arange(1,10)
print("x = ", x)
print("valor mínimo de x = ", x.min())
print("valor mínimo de x = ", min(x))
print("valor máximo de x = ", x.max())
print("valor máximo de x = ", max(x))
print("soma dos elementos de x = ", x.sum())
print("soma dos elementos de x = ", sum(x))

In [ ]:
# Exemplos de uso de funções estatísticas
print("média dos valores dos elementos de x = ", x.mean())
print("desvio padrão dos valores dos elementos de x = ", x.std())

In [ ]:
print("Os dois comandos print() abaixo estão corretos?")
# print("média dos valores dos elementos de x = ", mean(x))
#print("desvio padrão dos valores dos elementos de x = ", std(x))

In [ ]:
# Exemplo de uso de funções estatísticas sobre Arrays Numpy
x = np.arange(1,10)
print("x = ", x)
print("valor mínimo de x = ", np.min(x))
print("valor máximo de x = ", np.max(x))
print("soma dos elementos de x = ", np.sum(x))
print("média dos valores dos elementos de x = ", np.mean(x))
print("mediana dos valores dos elementos de x = ", np.median(x))
print("desvio padrão dos valores dos elementos de x = ", np.std(x))
print("variância dos valores dos elementos de x = ", np.var(x))
print("desvio padrão dos valores dos elementos de x = ", np.sqrt(np.var(x)))

Como visto anteriormente, os métodos específicos do Numpy são mais eficientes computacionalmente do que métodos padrões.

A seguir verifique o desempenho de métodos estatísticos específicos do Numpy com relação aos métodos gerais.

In [ ]:
# Exemplo - Avaliação de método genérico e método específico do Numpy
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

In [ ]:
# Exercício - Avalie o desempenho dos métodos genérico e específico
# para cálculo de desvio padrão
# Utilize o Array big_array



Para se realizar operações matriciais com Arrays Numpy é necessário utilizar métodos.
- np.dot(x,y) --> x*y
- x.dot(y) --> x*y
- np.inv
- np.mat.T  --> $mat^T$

In [95]:
# Exemplo de uso de métodos para operação matricial em Arrays Numpy
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z1 = x.dot(y) 
z2 = np.dot(x, y)
print("z1 = \n", z1)
print("\nz2 = \n", z2)

z1 = 
 [[  28.   64.]
 [  67.  181.]]

z2 = 
 [[  28.   64.]
 [  67.  181.]]


O programa abaixo implementa a seguinte equação matricial:

$mat_2 = mat_1^T * mat_1$

In [114]:
import numpy as np

mat1 = np.array([[1., 2., 3.], [4.5, .5, 6.7], [7.3,1.8,2.7]]) 
mat2 = mat1.T.dot(mat1)
print("mat1 = \n", mat1)
print("mat2 = \n", mat2)

mat1 = 
 [[ 1.   2.   3. ]
 [ 4.5  0.5  6.7]
 [ 7.3  1.8  2.7]]
mat2 = 
 [[ 74.54  17.39  52.86]
 [ 17.39   7.49  14.21]
 [ 52.86  14.21  61.18]]


In [115]:
#from numpy.linalg import inv
np.linalg.inv(mat1)

array([[ -1.40625000e-01,   1.27802812e-20,   1.56250000e-01],
       [  4.82668067e-01,  -2.52100840e-01,   8.92857143e-02],
       [  5.84296218e-02,   1.68067227e-01,  -1.11607143e-01]])

In [116]:
# Para evitar explicitar o caminho do método no pacote
from numpy.linalg import inv
inv(mat1)

array([[ -1.40625000e-01,   1.27802812e-20,   1.56250000e-01],
       [  4.82668067e-01,  -2.52100840e-01,   8.92857143e-02],
       [  5.84296218e-02,   1.68067227e-01,  -1.11607143e-01]])

In [117]:
# A multiplicação de uma matriz por sua inversa é uma matriz Identidade
mat1.dot(inv(mat1))

array([[  1.00000000e+00,  -2.77555756e-17,   5.55111512e-17],
       [  9.15642445e-17,   1.00000000e+00,   9.67480064e-17],
       [  8.29751767e-18,  -6.22751150e-18,   1.00000000e+00]])

In [118]:
# A multiplicação de uma matriz por sua inversa é uma matriz Identidade
np.dot(mat1,inv(mat1))

array([[  1.00000000e+00,  -2.77555756e-17,   5.55111512e-17],
       [  9.15642445e-17,   1.00000000e+00,   9.67480064e-17],
       [  8.29751767e-18,  -6.22751150e-18,   1.00000000e+00]])

In [130]:
# O mesmo problema ocorre com o método determinante
print("Determinante de mat1 = ", np.linalg.det(mat1))

from numpy.linalg import det
print("Determinante de mat1 = ", det(mat1))

Determinante de mat1 =  76.16
Determinante de mat1 =  76.16


Exercício:

Calcule a seguinte expressão matricial (use os vetores e matrizes já definidos anteriormente)

$ mat_3 = mat_1 * (mat_2)^{-1} * mat_1^T$

In [ ]:
# Resolução do exercício
# Utilize mat1 e mat2 definidos acima

???????

print("Valor de mat3 = \n", mat3)

Classe Matriz em Numpy
- O Pacote Numpy possui uma classe especial de Array (uni e bidimensonal) denominada de matriz.
- Esse tipo de classe possui métodos específicos
- Matrizes necessitam ser bidimensionais.
    - Para se utilizar estrutura com dimensão maior que 2, prezamos utilizar Arrays Numpy
- As operações sobre o "tipo" matriz são operações matriciais, como em Matlab.
    - Operações sobre Arrays são operações elemento a elemento.



In [ ]:
# Exemplo de uso do tipo Matriz do Numpy
import numpy as np

x1 = np.array([1, 2, 3], float) # definição de um Array unidimensional de 03 posições float

x2 = np.matrix(x1) #  Transformanda o tipo Array em tipo Matriz

x2

In [ ]:
type(x2)

In [ ]:
# Exemplo de uso do tipo Matriz do Numpy
print("Exemplo de uso do método Tranposta de Matriz")
x3 = np.array([[1,2,3],[4,5,6]],float)  # esse passo não é necessário
x4 = np.matrix(x3)
x5 = np.mat(x4).transpose() 
x5



In [ ]:
# Exemplo de uso do tipo Matriz do Numpy
print("Exemplo de uso do método 'Tranposta de Matriz'")
x4 = np.matrix([[1,2,3],[4,5,6]],float) # pode-se converter tipo Lista diretamente para tipo Matriz
x5 = x4.T
# x5 = np.mat(x4).T # transport matriz via método de classe
# x5 = np.mat(x4).transpose()   # método para transpor matriz
x5

In [151]:
# Outra opção para se inicializar Matrices Numpy
np.matrix("[1 2 3; 4 5 6]")

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Exemplo de uso do tipo Matriz do Numpy
print("Exemplo de uso do criação de uma Matriz Identidade")
mat0 = np.eye(5)  # matriz identidade de ordem 5 - ainda é tipo array
#mat0 = np.identity(5)
print(4*mat0)

In [ ]:
# Transformar Array Identidade para Matriz Identidade
print(type(mat0))
mat1 = np.matrix(mat0)
print(type(mat1))

In [ ]:
# Exercício

print("O que ocorre quando se multiplica um Array por uma Matriz?")
print("Escreva um programa para investigado isto")




In [ ]:
# Exemplos de uso de operadores sobre tipo Matriz do Numpy
vet1 = np.matrix([1,2,3],float)   # vetor linha 1x3
vet2 = np.matrix([[2],[4],[6]],float)   # vetor coluna 3x1
mat1 = np.matrix ([[1,2,3],[4,5,6], [7,8,9]],float) # matriz 3x3
mat2 = np.eye(3)   # matriz identidade 3x3

print("2*mat1*mat2 = \n", 2*mat1*mat2)
print("\nvet1*mat1*vet2 = \n", vet1*mat1*vet2)

Exercício:

Calcule a seguinte expressão matricial (use os vetores e matrizes já definidos anteriormente)

$ mat3 = (mat1^T * mat1) * vet1^T$

In [ ]:
# Solução do exercício

?????????
print("mat3 = \n")
print(mat3)

In [ ]:
# Exemplo de uso de inversa de matriz
mat1 = np.matrix ([[1,2,3],[4.7,1.5,2.6], [-3,8.7,1.9]],float) # matriz 3x3
print("Matriz mat1 = \n", mat1)
print("\nMatriz inversa de mat1 = \n", mat1.I)

Exercício:

Calcule a seguinte expressão matricial (use os vetores e matrizes já definidos anteriormente)

$ mat3 = vet1 * (mat1^T * mat1)^{-1} * vet1^T$

In [ ]:
# Solução do exercício

?????????
print("mat3 = \n")
print(mat3)

A baixo são apresentadas as abordagens via array e matriz para para o seguinte cálculo matricial:
- $z = y^T * X * y $

In [138]:
# Geração do Array bidimensional X  (Matriz 4x4)
X = np.array([[ 8.82768214, 3.82222409, -1.14276475, 2.04411587],[ 3.82222409, 6.75272284, 0.83909108, 2.08293758],[-1.14276475, 0.83909108, 5.01690521, 0.79573241],[ 2.04411587, 2.08293758, 0.79573241, 6.24095859]])

y = X[:, :1]    # Obtenção do vetor y (array 4x1) 

np.dot(y.T, np.dot(X, y))


array([[ 1195.46796121]])

In [139]:
# Versão da solução acima utilizando-se a classe Matriz
Xm = np.matrix(X)
ym = Xm[:, 0]
ym.T * Xm * ym

matrix([[ 1195.46796121]])

In [140]:
Xm.I * Xm

matrix([[  1.00000000e+00,   0.00000000e+00,  -5.55111512e-17,
           5.55111512e-17],
        [ -1.11022302e-16,   1.00000000e+00,   2.77555756e-17,
          -5.55111512e-17],
        [  1.11022302e-16,   0.00000000e+00,   1.00000000e+00,
           0.00000000e+00],
        [ -5.55111512e-17,  -5.55111512e-17,   2.77555756e-17,
           1.00000000e+00]])

In [141]:
Xm.I * X

matrix([[  1.00000000e+00,   0.00000000e+00,  -5.55111512e-17,
           5.55111512e-17],
        [ -1.11022302e-16,   1.00000000e+00,   2.77555756e-17,
          -5.55111512e-17],
        [  1.11022302e-16,   0.00000000e+00,   1.00000000e+00,
           0.00000000e+00],
        [ -5.55111512e-17,  -5.55111512e-17,   2.77555756e-17,
           1.00000000e+00]])

In [149]:
# Obs.: Para se fazer multiplicação elemento a elemento com Matrizes,
# precisamos utilizar o método multiply

np.multiply(Xm,Xm)

matrix([[ 77.92797196,  14.60939699,   1.30591127,   4.17840969],
        [ 14.60939699,  45.59926575,   0.70407384,   4.33862896],
        [  1.30591127,   0.70407384,  25.16933789,   0.63319007],
        [  4.17840969,   4.33862896,   0.63319007,  38.94956412]])